project:
  type: website

website:
  title: "RETINA Workshop Series on Anomaly Detection" 
  google-analytics: "UA-267334165"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pridiltal
      - icon: twitter
        href: https://twitter.com/retinalab
format:
  html:
    theme: cosmo
    css: styles.css



